draw_set_font(ft_text)
draw_set_halign(fa_left)
draw_text(32, 48, "Time: " + string(hour) +":00")
draw_text(32, 64, "Day: " + string(day))
draw_text(32, 80, "Tribe: " + string(current_tribe.name))
draw_text(32, 96, "Relationship: " + relationship)
